// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rcm.Crm;

#nullable disable

namespace Rcm.Crm.Migrations
{
    [DbContext(typeof(CrmDb))]
    [Migration("20260923131019_InitialCrm")]
    partial class InitialCrm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rcm.Crm.CommandReceipt", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeamId", "ActorId", "RequestId");

                    b.ToTable("Receipts", "crm");
                });

            modelBuilder.Entity("Rcm.Crm.ContactEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextAction")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextDate")
                        .HasColumnType("date");

                    b.Property<string>("NextDescription")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "TopicId", "RecordedAt", "Id");

                    b.ToTable("Events", "crm");
                });

            modelBuilder.Entity("Rcm.Crm.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedPhone")
                        .HasColumnType("text");

                    b.Property<string>("OriginalNote")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "NormalizedEmail");

                    b.HasIndex("TeamId", "NormalizedPhone");

                    b.HasIndex("TeamId", "DisplayName", "Id");

                    b.ToTable("Customers", "crm");
                });

            modelBuilder.Entity("Rcm.Crm.CustomerChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CustomerId");

                    b.ToTable("CustomerChanges", "crm");
                });

            modelBuilder.Entity("Rcm.Crm.Membership", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("TeamId");

                    b.ToTable("Memberships", "crm");
                });

            modelBuilder.Entity("Rcm.Crm.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Teams", "crm");
                });

            modelBuilder.Entity("Rcm.Crm.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Need")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("NextAction")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("NextDate")
                        .HasColumnType("date");

                    b.Property<string>("NextDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.PrimitiveCollection<string[]>("Products")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CustomerId");

                    b.HasIndex("TeamId", "NextDate", "Id");

                    b.ToTable("Topics", "crm", t =>
                        {
                            t.HasCheckConstraint("CK_Topic_Plan", "NOT (\"NextDate\" IS NOT NULL AND \"NextDescription\" IS NOT NULL) AND (\"State\" <> 'closed' OR (\"NextDate\" IS NULL AND \"NextDescription\" IS NULL AND \"NextAction\" IS NULL))");
                        });
                });

            modelBuilder.Entity("Rcm.Crm.ContactEvent", b =>
                {
                    b.HasOne("Rcm.Crm.Topic", "Topic")
                        .WithMany("Events")
                        .HasForeignKey("TeamId", "TopicId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Rcm.Crm.Customer", b =>
                {
                    b.HasOne("Rcm.Crm.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Rcm.Crm.CustomerChange", b =>
                {
                    b.HasOne("Rcm.Crm.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("TeamId", "CustomerId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Rcm.Crm.Membership", b =>
                {
                    b.HasOne("Rcm.Crm.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Rcm.Crm.Topic", b =>
                {
                    b.HasOne("Rcm.Crm.Customer", "Customer")
                        .WithMany("Topics")
                        .HasForeignKey("TeamId", "CustomerId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Rcm.Crm.Customer", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Rcm.Crm.Topic", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
